name: Report a Bug
description: The game crashed or something is not working as expected.
labels: [Bug]
projects: TwelveIterationMods/3
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Filling out this information and **providing logs** will help get the issue resolved faster.

        > [!WARNING]
        > Do not download any files from comments on GitHub. Malicious users may try to trick you into installing malware.
  - type: dropdown
    id: minecraftVersion
    attributes:
      label: Minecraft Version
      description: What version of Minecraft were you running?
      options:
        - 1.21.9
        - 1.21.8
        - 1.21.5
        - 1.21.4
        - 1.21.1 (LTS)
        - 1.20.1 (LTS)
        - Other (specify below)
    validations:
      required: true
  - type: dropdown
    id: modLoader
    attributes:
      label: Mod Loader
      description: What mod loader were you using?
      options:
        - NeoForge
        - Fabric
        - Forge
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: Be as thorough as possible and provide a step-by-step guide to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Click this field and drag your latest.log file into it to upload it. You can use also post a link to a site like pastebin, but make sure they are set to not expire.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > [!WARNING]
        > Logs are **required**. You can find them in the logs folder of your Minecraft instance.
        > 
        > Failure to provide logs may result in your ticket being closed.

