name: Report a Bug
description: The game crashed or something is not working as expected.
labels: [Bug]
projects: TwelveIterationMods/3
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Filling out this information and **providing logs** will help get the issue resolved faster.

        > [!WARNING]
        > **Note:** Do not download any files offered in comment responses. Malicious users may try tricking you into installing malware.
  - type: dropdown
    id: minecraftVersion
    attributes:
      label: Minecraft Version
      description: What version of Minecraft were you running?
      options:
        - 1.21.4
        - 1.21.1 (LTS)
        - 1.20.1 (LTS)
        - Other (specify below)
    validations:
      required: true
  - type: dropdown
    id: modLoader
    attributes:
      label: Mod Loader
      description: What mod loader were you using?
      options:
        - NeoForge
        - Fabric
        - Forge
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: Be as thorough as possible and provide a step-by-step guide to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Click this field and drag your latest.log file into it to upload it. You can use also post a link to a site like pastebin, but make sure they are set to not expire.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > [!WARNING]
        > **Note:** If you are using 
        > - custom server distributions (e.g. SpongeForge, Arclight), or
        > - performance mods (e.g. C2ME, Redirector), or
        > - bridging mods (e.g. Sinytra Connector, Polymer)
        > you must test if the issue occurs without them before reporting.
